application: sharp-imprint-787
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: MySQLdb
  version: "1.2.4b4"
- name: django
  version: "1.4"
- name: pycrypto
  version: "2.6"

builtins:
- django_wsgi: on

handlers:
- url: /static
  static_dir: static
  expiration: '0'